.PHONY: clean All

All:
	@echo "----------Building project:[ FinalProject - Debug ]----------"
	@"$(MAKE)" -f  "FinalProject.mk"
clean:
	@echo "----------Cleaning project:[ FinalProject - Debug ]----------"
	@"$(MAKE)" -f  "FinalProject.mk" clean
